version: '3.8'

## Container debugging:
# 1. append the following lines to desired container
# 2. boot up the container using `docker-compose up -d`
# 3 run `docker exec -it <container-name> bash` to start interactive shell
#
#    tty: true
#    stdin_open: true
#    entrypoint: bash

services:
  fhir-converter:
    container_name: built-fhir-converter
    hostname: fhir-converter
    restart: unless-stopped
    image: ghcr.io/b-techbw/openhim-mediator-fhir-converter:local
    build: ./
    ports:
      - 2019:2019
      - 9229:9229
    volumes:
      - ./config.json:/app/config.json
      - ./data/templates:/app/data/service-templates
    entrypoint: ./deploy/debug.sh
    networks:
      - hie
    # tty: true
    # stdin_open: true
    # entrypoint: bash

networks:
  hie:
    external: true
    name: hie-botswana_hie
