name: Node.js CI

on: 
  push:
    branches:
      - "handlebars"
  pull_request:
    branches:
      - "handlebars"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.17]

    steps:
    - uses: actions/checkout@v2
    - name: Set Up Java Environment
      run: sudo apt update && sudo apt install openjdk-11-jdk
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn build
    - run: yarn test
      env:
        CI: true
